
/* ============================================================================
   RISK MODULE CONFIGURATION
   Drives the "Master Table Preparation" landing cards on #risk-categories
   ============================================================================ */
%macro riskModulesConfig;
    put 'const riskModulesConfig = Object.freeze([';
    put '  {';
    put '    key: "regulatory",';
    put '    title: "SACCR and CVA",';
    put '    description: "Comprehensive regulatory compliance reports and monitoring dashboards for regulatory authorities.",';
    put '    iconChar: "SC",';
    put '    route: "#saccr-cva"';
    put '  },';
    put '  {';
    put '    key: "credit",';
    put '    title: "SAMA Q17",';
    put '    description: "Advanced credit risk assessment, portfolio analysis and default probability modeling.",';
    put '    iconChar: "Q17",';
    put '    route: "#sama-q17"';
    put '  },';
    put '  {';
    put '    key: "operational",';
    put '    title: "IRRBB",';
    put '    description: "Operational risk identification, assessment and mitigation strategies across all business units.",';
    put '    iconChar: "IR",';
    put '    route: "#sama-p3"';
    put '  },';
    put '  {';
    put '    key: "market",';
    put '    title: "Assets",';
    put '    description: "Real-time market risk monitoring, VaR calculations and stress testing scenarios.",';
    put '    iconChar: "AS",';
    put '    route: "#assets",';
    put '    stats: [';
    put '      { label: "VaR (95%)", value: "$45M" },';
    put '      { label: "Volatility", value: "12.5%" }';
    put '    ]';
    put '  },';
    put '  {';
    put '    key: "liquidity",';
    put '    title: "Liabilities",';
    put '    description: "Liquidity risk assessment, cash flow projections and funding stability analysis.",';
    put '    iconChar: "LB",';
    put '    route: "#liability",';
    put '    stats: [';
    put '      { label: "LCR Ratio", value: "145%" },';
    put '      { label: "HQLA", value: "$850M" }';
    put '    ]';
    put '  },';
    put '  {';
    put '    key: "icaap",';
    put '    title: "Off Balance Sheet",';
    put '    description: "Internal Capital Adequacy Assessment Process and capital planning strategies.",';
    put '    iconChar: "OB",';
    put '    route: "#offbalance",';
    put '    stats: [';
    put '      { label: "CAR", value: "18.5%" },';
    put '      { label: "Capital", value: "$2.8B" }';
    put '    ]';
    put '  },';
    put '  {';
    put '    key: "ilaap",';
    put '    title: "Customer",';
    put '    description: "Internal Liquidity Adequacy Assessment Process and liquidity risk management.",';
    put '    iconChar: "CT",';
    put '    route: "#customer",';
    put '    stats: [';
    put '      { label: "NSFR", value: "125%" },';
    put '      { label: "Stable Funding", value: "$1.2B" }';
    put '    ]';
    put '  }';
    put ']);';
%mend riskModulesConfig;
