/* ============================================================================
   MT UTILITIES MODULE
   Common utility functions for the Master Table Generation application
   ============================================================================ */

%macro generate_javascript_utils;
    put '// MT Utilities Module';
    put 'const MTUtils = {';
    put '  showLoading() {';
    put '    const loading = document.getElementById("loading");';
    put '    if (loading) loading.style.display = "flex";';
    put '  },';
    put '  hideLoading() {';
    put '    const loading = document.getElementById("loading");';
    put '    if (loading) loading.style.display = "none";';
    put '  },';
    put '  showNotification(message, type = "success") {';
    put '    const notification = document.getElementById("notification");';
    put '    const notificationText = document.getElementById("notification-text");';
    put '    if (!notification || !notificationText) return;';
    put '    notification.className = `notification ${type}`;';
    put '    notificationText.textContent = message;';
    put '    notification.classList.add("show");';
    put '    setTimeout(() => notification.classList.remove("show"), 4000);';
    put '  },';
    put '  closeModal() {';
    put '    const modal = document.getElementById("reportModal");';
    put '    if (modal) modal.classList.remove("show");';
    put '  },';
    put '  formatValue(value) {';
    put '    if (typeof value === "number") {';
    put '      if (value >= 1000000) return "$" + (value / 1000000).toFixed(1) + "M";';
    put '      else if (value >= 1000) return value.toLocaleString();';
    put '      else return value.toFixed(1);';
    put '    }';
    put '    return value;';
    put '  },';
    put '  formatLabel(key) {';
    put '    return key.replace(/([A-Z])/g, " $1").replace(/^./, str => str.toUpperCase());';
    put '  },';
    put '  getTodayDate() {';
    put '    return new Date().toISOString().split("T")[0];';
    put '  },';
    put '  isValidDate(dateString) {';
    put '    if (!dateString || dateString.trim() === "") return false;';
    put '    const date = new Date(dateString);';
    put '    return date instanceof Date && !isNaN(date);';
    put '  },';
    put '  debounce(func, wait) {';
    put '    let timeout;';
    put '    return function executedFunction(...args) {';
    put '      const later = () => {';
    put '        clearTimeout(timeout);';
    put '        func(...args);';
    put '      };';
    put '      clearTimeout(timeout);';
    put '      timeout = setTimeout(later, wait);';
    put '    };';
    put '  },';
    put '  throttle(func, limit) {';
    put '    let inThrottle;';
    put '    return function() {';
    put '      const args = arguments;';
    put '      const context = this;';
    put '      if (!inThrottle) {';
    put '        func.apply(context, args);';
    put '        inThrottle = true;';
    put '        setTimeout(() => inThrottle = false, limit);';
    put '      }';
    put '    };';
    put '  }';
    put '};';
    put '// Global functions for backward compatibility';
    put 'function showLoading() { MTUtils.showLoading(); }';
    put 'function hideLoading() { MTUtils.hideLoading(); }';
    put 'function showNotification(message, type) { MTUtils.showNotification(message, type); }';
    put 'function closeModal() { MTUtils.closeModal(); }';
%mend generate_javascript_utils;
