
/* ============================================================================
   SACCR SUMMARY STORED PROCESS BACKEND
   SAS Stored Process entry point: SACCR_CVA_2

   Input parameter (POST body):
     reporting_date — ISO date string sent by the frontend (e.g. "2025-12-31")
                      Available as macro variable &reporting_date.

   Output:
     JSON written to _webout — consumed by MTSaccrResults.render() in the
     Master Table Generation dashboard.

   JSON structure (keys must match saccrResultsView.sas COLUMN_MAPS):
     {
       saccr_header      : [ one aggregate row — KPI stat cards ],
       cva_header        : [],
       summary_table     : [ one row per netting set ],
       comparison_report : [],
       exception_report  : []
     }
   ============================================================================ */


/* Set HTTP response content type to JSON */
data _null_;
    rc = stpsrv_header('Content-type', 'application/json;charset=utf-8');
run;


/* ── Step 1: Filter source table by reporting date ── */
data SACCR_SUMMARY(
    keep = As_of_date
           Netting_set_id
           NUMBER_OF_TRADES
           NOTIONAL_AMOUNT_LCY_ABS
           REPLACEMENT_COST
           PFE
           EAD
           RWA
           SACCR_CAPITAL_CHARGE
);
    set orc_lib.SACCR_SUMMARY_AGG_NS(
        where=(datepart(As_of_date) = "&reporting_date."d)
    );
run;


/* ── Step 2: Aggregate header KPIs (one summary row) ── */
proc summary data=SACCR_SUMMARY;
    var NUMBER_OF_TRADES REPLACEMENT_COST PFE EAD SACCR_CAPITAL_CHARGE;
    output out=SACCR_HEADER(
        drop   = _TYPE_
        rename = (_FREQ_ = number_of_netting_sets)
    )
        sum(NUMBER_OF_TRADES)      = number_of_trades
        sum(REPLACEMENT_COST)      = rc_net_margined_yl
        sum(PFE)                   = pfe
        sum(EAD)                   = ead
        sum(SACCR_CAPITAL_CHARGE)  = saccr_charge;
run;


/* ── Step 3: Write JSON to _webout ── */
proc json out=_webout pretty nosastags;
    write open object;

    /* Aggregate KPI row — rendered as stat cards in the dashboard */
    write values "saccr_header";
    export SACCR_HEADER / nosastags;

    /* CVA data not available from this dataset — return empty array */
    write values "cva_header";
    write open array;
    write close;

    /* One row per netting set — rendered in the SACCR Summary tab table */
    write values "summary_table";
    export SACCR_SUMMARY / nosastags;

    /* Comparison and exception reports not generated by this process */
    write values "comparison_report";
    write open array;
    write close;

    write values "exception_report";
    write open array;
    write close;

    write close;
run;
