/* ============================================================================
   MT UI MODULE
   Handles DOM manipulation, animations, and UI interactions
   ============================================================================ */

%macro generate_javascript_ui;
    put '// MT UI Module';
    put 'const MTUI = {';
    put '  animateStats() {';
    put '    const stats = [';
    put '      { element: "total-reports", target: 156, suffix: "" },';
    put '      { element: "active-users", target: 42, suffix: "" },';
    put '      { element: "risk-score", target: 7.2, suffix: "" },';
    put '      { element: "compliance-rate", target: 98.5, suffix: "%" }';
    put '    ];';
    put '    stats.forEach(stat => this.animateNumber(stat.element, stat.target, stat.suffix));';
    put '  },';
    put '  animateNumber(elementId, target, suffix) {';
    put '    const element = document.getElementById(elementId);';
    put '    if (!element) return;';
    put '    const duration = 2000;';
    put '    const start = 0;';
    put '    const increment = target / (duration / 16);';
    put '    let current = start;';
    put '    const timer = setInterval(() => {';
    put '      current += increment;';
    put '      if (current >= target) {';
    put '        current = target;';
    put '        clearInterval(timer);';
    put '      }';
    put '      if (suffix === "%") {';
    put '        element.textContent = current.toFixed(1) + suffix;';
    put '      } else if (target >= 1000) {';
    put '        element.textContent = Math.floor(current).toLocaleString() + suffix;';
    put '      } else {';
    put '        element.textContent = current.toFixed(1) + suffix;';
    put '      }';
    put '    }, 16);';
    put '  },';
    put '  updateStats() {';
    put '    const totalReportsElement = document.getElementById("total-reports");';
    put '    if (!totalReportsElement) return;';
    put '    const randomIncrement = Math.random() * 5;';
    put '    const currentReports = parseInt(totalReportsElement.textContent.replace(",", ""));';
    put '    totalReportsElement.textContent = (currentReports + Math.floor(randomIncrement)).toLocaleString();';
    put '  },';
    put '  initializeEventListeners() {';
    put '    const modal = document.getElementById("reportModal");';
    put '    if (modal) {';
    put '      modal.addEventListener("click", (e) => {';
    put '        if (e.target === modal) MTUtils.closeModal();';
    put '      });';
    put '    }';
    put '    document.addEventListener("keydown", (e) => {';
    put '      if (e.key === "Escape") MTUtils.closeModal();';
    put '    });';
    put '    window.addEventListener("resize", MTUtils.debounce(() => {';
    put '      const sidebar = document.getElementById("sidebar");';
    put '      if (window.innerWidth > 1024 && sidebar) {';
    put '        sidebar.classList.remove("show");';
    put '      }';
    put '    }, 250));';
    put '  },';
    put '  initializeAnimations() {';
    put '    setTimeout(() => this.animateStats(), 500);';
    put '  },';
    put '  setDefaultDates(reportId) {';
    put '    const today = MTUtils.getTodayDate();';
    put '    const dateInputs = document.querySelectorAll(''input[type="date"]'');';
    put '    dateInputs.forEach(input => {';
    put '      if (input.id && input.id.includes(reportId) && !input.value) {';
    put '        input.value = today;';
    put '      }';
    put '    });';
    put '  }';
    put '};';
%mend generate_javascript_ui;
