
/* ============================================================================
   MASTER TABLE REPORT GENERATION MODULE
   Executes the stored procedure backing a report prompt card and reports
   back to the user via the shared notification banner.
   ============================================================================ */
%macro masterTableReportGeneration;
    put '// MT Report Generation Module';
    put 'const MTReports = {';
    put '  // Finds the date input for a report card, trying its known id suffixes';
    put '  resolveReportDate(reportType) {';
    put '    let dateInput = document.getElementById(reportType + "-asof");';
    put '    if (!dateInput) dateInput = document.getElementById(reportType + "-date");';
    put '    if (!dateInput) dateInput = document.getElementById(reportType + "-asof1");';
    put '    return dateInput ? dateInput.value : null;';
    put '  },';
    put '  // Validates the form, then POSTs the date(s) to the report stored process';
    put '  generateRegulatoryReport(reportType) {';
    put '    const selectedDate = this.resolveReportDate(reportType);';
    put '    console.log("Generating " + reportType + " report for date: " + selectedDate);';
    put '    if (!selectedDate || selectedDate.trim() === "") {';
    put '      MTUtils.showNotification("Please select a valid date for the report", "error");';
    put '      return;';
    put '    }';

    /* ── SAMA Q17 Data Preparation: dataset-selection + availability gate ── */
    put '    if (reportType === "sama-q17-2") {';
    put '      var selectedDatasets = getSelectedDatasets(reportType);';
    put '      if (selectedDatasets.length === 0) {';
    put '        showModalMessage({ title: "No Dataset Selected", message: "Please select at least one dataset before running the process.", type: "warning" });';
    put '        return;';
    put '      }';
    put '      var checkUrl = masterTableAvailabilityEndpoints && masterTableAvailabilityEndpoints[reportType];';
    put '      if (!checkUrl) {';
    put '        MTUtils.showNotification("Availability check endpoint not yet configured for this report.", "error");';
    put '        return;';
    put '      }';
    put '      MTUtils.showLoading();';
    put '      var checkData = new URLSearchParams();';
    put '      checkData.append("reporting_date", selectedDate);';
    put '      checkData.append("datasets", selectedDatasets.join(","));';
    put '      fetch(checkUrl, {';
    put '        method: "POST",';
    put '        headers: { "Content-Type": "application/x-www-form-urlencoded", "Accept": "application/json" },';
    put '        body: checkData.toString()';
    put '      })';
    put '      .then(function (response) {';
    put '        if (!response.ok) throw new Error("Availability check failed: " + response.status);';
    put '        return response.json();';
    put '      })';
    put '      .then(function (availability) {';
    put '        MTUtils.hideLoading();';
    put '        var readyDatasets = [];';
    put '        var pendingDatasets = [];';
    put '        selectedDatasets.forEach(function (k) {';
    put '          if (availability[k] === true) readyDatasets.push(k);';
    put '          else pendingDatasets.push(k);';
    put '        });';
    put '        if (pendingDatasets.length > 0) {';
    put '          showDatasetStatusModal(readyDatasets, pendingDatasets);';
    put '          return;';
    put '        }';
    put '        MTReports.runSamaQ17DataPrep(reportType, selectedDate, selectedDatasets);';
    put '      })';
    put '      .catch(function (error) {';
    put '        MTUtils.hideLoading();';
    put '        MTUtils.showNotification("Error verifying dataset availability: " + error.message, "error");';
    put '      });';
    put '      return;';
    put '    }';

    /* ── Standard report execution path ── */
    put '    const storedProcedureUrl = masterTableReportEndpoints[reportType];';
    put '    if (!storedProcedureUrl) {';
    put '      MTUtils.showNotification("No stored procedure endpoint configured for " + reportType + " yet", "error");';
    put '      return;';
    put '    }';
    put '    MTUtils.showLoading();';
    put '    const formData = new URLSearchParams();';
    put '    formData.append("reporting_date", selectedDate);';
    put '    if (reportType === "sama-p3") {';
    put '      const londonDateInput = document.getElementById(reportType + "-londonDate");';
    put '      if (londonDateInput && londonDateInput.value) {';
    put '        formData.append("london_date", londonDateInput.value);';
    put '      }';
    put '    }';
    put '    const isJsonReport = reportType === "saccr-cva";';
    put '    fetch(storedProcedureUrl, {';
    put '      method: "POST",';
    put '      headers: {';
    put '        "Content-Type": "application/x-www-form-urlencoded",';
    put '        "Accept": isJsonReport ? "application/json" : "text/html"';
    put '      },';
    put '      body: formData.toString()';
    put '    })';
    put '    .then(response => {';
    put '      if (!response.ok) {';
    put '        throw new Error("Network response was not ok: " + response.status);';
    put '      }';
    put '      return isJsonReport ? response.json() : response.text();';
    put '    })';
    put '    .then(responseData => {';
    put '      if (isJsonReport) {';
    put '        MTSaccrResults.render(reportType, responseData);';
    put '      }';
    put '      MTUtils.showNotification("Master Table Prepared Successfully", "success");';
    put '      MTUtils.hideLoading();';
    put '    })';
    put '    .catch(error => {';
    put '      MTUtils.hideLoading();';
    put '      if (isJsonReport && typeof SACCR_SAMPLE_DATA !== "undefined") {';
    put '        MTSaccrResults.render(reportType, SACCR_SAMPLE_DATA);';
    put '        MTUtils.showNotification("Live data unavailable — showing sample data", "info");';
    put '      } else {';
    put '        MTUtils.showNotification("Error generating Master Tables: " + error.message, "error");';
    put '      }';
    put '    });';
    put '  },';

    /* ── SAMA Q17 Data Prep execution (called after availability confirmed) ── */
    put '  runSamaQ17DataPrep(reportType, selectedDate, selectedDatasets) {';
    put '    var runUrl = masterTableReportEndpoints[reportType];';
    put '    if (!runUrl) {';
    put '      MTUtils.showNotification("No stored procedure endpoint configured for " + reportType + " yet", "error");';
    put '      return;';
    put '    }';
    put '    MTUtils.showLoading();';
    put '    var formData = new URLSearchParams();';
    put '    formData.append("reporting_date", selectedDate);';
    put '    formData.append("datasets", selectedDatasets.join(","));';
    put '    var runTypeEl = document.getElementById(reportType + "-RunType");';
    put '    if (runTypeEl && runTypeEl.value) formData.append("run_type", runTypeEl.value);';
    put '    var londonEl = document.getElementById(reportType + "-londonDate");';
    put '    if (londonEl && londonEl.value) formData.append("london_date", londonEl.value);';
    put '    fetch(runUrl, {';
    put '      method: "POST",';
    put '      headers: { "Content-Type": "application/x-www-form-urlencoded", "Accept": "text/html" },';
    put '      body: formData.toString()';
    put '    })';
    put '    .then(function (response) {';
    put '      if (!response.ok) throw new Error("Network response was not ok: " + response.status);';
    put '      return response.text();';
    put '    })';
    put '    .then(function () {';
    put '      MTUtils.showNotification("Master Table Prepared Successfully", "success");';
    put '      MTUtils.hideLoading();';
    put '    })';
    put '    .catch(function (error) {';
    put '      MTUtils.hideLoading();';
    put '      MTUtils.showNotification("Error generating Master Tables: " + error.message, "error");';
    put '    });';
    put '  },';
    put '  // Placeholder for the not-yet-built report history view';
    put '  viewReportHistory(reportType) {';
    put '    console.log("Viewing report history for:", reportType);';
    put '    MTUtils.showNotification("Report history feature coming soon", "info");';
    put '  }';
    put '};';
    put '// Global functions for backward compatibility';
    put 'function generateRegulatoryReport(reportType) { MTReports.generateRegulatoryReport(reportType); }';
    put 'function viewReportHistory(reportType) { MTReports.viewReportHistory(reportType); }';
%mend masterTableReportGeneration;
