/* ============================================================================
   ARCHIVED - LEGACY MONOLITHIC JAVASCRIPT MODULE
   Superseded by the config-driven modules under javascript/{router,routes,
   reportGeneration,utils,ui}. Kept for reference only - NOT included by
   javascript/index.sas and NOT part of the build.
   ============================================================================ */


/* ============================================================================
   JAVASCRIPT UTILITIES
   ============================================================================ */
%macro generate_javascript_utils;
    put '<script>';
    put 'function showLoading() { document.getElementById("loading").style.display = "flex"; }';
    put 'function hideLoading() { document.getElementById("loading").style.display = "none"; }';
    put 'function showNotification(message, type) {';
    put '  if (!type) type = "success";';
    put '  var notification = document.getElementById("notification");';
    put '  var notificationText = document.getElementById("notification-text");';
    put '  notification.className = "notification " + type;';
    put '  notificationText.textContent = message;';
    put '  notification.classList.add("show");';
    put '  setTimeout(function() { notification.classList.remove("show"); }, 4000);';
    put '}';
    put 'function closeModal() { document.getElementById("reportModal").classList.remove("show"); }';
    put '</script>';
%mend generate_javascript_utils;

/* ============================================================================
   JAVASCRIPT ANIMATIONS
   ============================================================================ */
%macro generate_javascript_animations;
    put '<script>';
    put 'function animateStats() {';
    put '  var stats = [';
    put '    { element: "total-reports", target: 156, suffix: "" },';
    put '    { element: "active-users", target: 42, suffix: "" },';
    put '    { element: "risk-score", target: 7.2, suffix: "" },';
    put '    { element: "compliance-rate", target: 98.5, suffix: "%" }';
    put '  ];';
    put '  for (var i = 0; i < stats.length; i++) {';
    put '    animateNumber(stats[i].element, stats[i].target, stats[i].suffix);';
    put '  }';
    put '}';
    put 'function animateNumber(elementId, target, suffix) {';
    put '  var element = document.getElementById(elementId);';
    put '  var duration = 2000;';
    put '  var start = 0;';
    put '  var increment = target / (duration / 16);';
    put '  var current = start;';
    put '  var timer = setInterval(function() {';
    put '    current += increment;';
    put '    if (current >= target) {';
    put '      current = target;';
    put '      clearInterval(timer);';
    put '    }';
    put '    if (suffix === "%") {';
    put '      element.textContent = current.toFixed(1) + suffix;';
    put '    } else if (target >= 1000) {';
    put '      element.textContent = Math.floor(current).toLocaleString() + suffix;';
    put '    } else {';
    put '      element.textContent = current.toFixed(1) + suffix;';
    put '    }';
    put '  }, 16);';
    put '}';
    put 'function updateStats() {';
    put '  var randomIncrement = Math.random() * 5;';
    put '  var currentReports = parseInt(document.getElementById("total-reports").textContent.replace(",", ""));';
    put '  document.getElementById("total-reports").textContent = (currentReports + Math.floor(randomIncrement)).toLocaleString();';
    put '}';
    put '</script>';
%mend generate_javascript_animations;

/* ============================================================================
   JAVASCRIPT MODAL HANDLERS
   ============================================================================ */
%macro generate_javascript_modal;
    put '<script>';
    put 'function displayReportDetails(reportResult) {';
    put '  var modal = document.getElementById("reportModal");';
    put '  var modalTitle = document.getElementById("modalTitle");';
    put '  var modalBody = document.getElementById("modalBody");';
    put '  modalTitle.textContent = reportResult.reportName;';
    put '  var summary = reportResult.data.summary;';
    put '  var details = reportResult.data.details;';
    put '  var html = "<div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 20px;\">";';
    put '  for (var key in summary) {';
    put '    if (summary.hasOwnProperty(key)) {';
    put '      html += "<div style=\"background: #f9fafb; padding: 15px; border-radius: 8px; text-align: center;\">";';
    put '      html += "<div style=\"font-size: 1.5rem; font-weight: 700; color: #1f2937; margin-bottom: 5px;\">" + formatValue(summary[key]) + "</div>";';
    put '      html += "<div style=\"font-size: 0.9rem; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px;\">" + formatLabel(key) + "</div>";';
    put '      html += "</div>";';
    put '    }';
    put '  }';
    put '  html += "</div><div style=\"margin-top: 20px;\">";';
    put '  html += "<h4 style=\"color: #1f2937; margin-bottom: 15px;\">Report Details</h4>";';
    put '  html += "<pre style=\"background: #f7fafc; padding: 15px; border-radius: 8px; overflow-x: auto; font-size: 0.9rem;\">" + JSON.stringify(details, null, 2) + "</pre>";';
    put '  html += "</div>";';
    put '  modalBody.innerHTML = html;';
    put '  modal.classList.add("show");';
    put '}';
    put 'function formatValue(value) {';
    put '  if (typeof value === "number") {';
    put '    if (value >= 1000000) {';
    put '      return "$" + (value / 1000000).toFixed(1) + "M";';
    put '    } else if (value >= 1000) {';
    put '      return value.toLocaleString();';
    put '    } else {';
    put '      return value.toFixed(1);';
    put '    }';
    put '  }';
    put '  return value;';
    put '}';
    put 'function formatLabel(key) {';
    put '  return key.replace(/([A-Z])/g, " $1").replace(/^./, function(str) { return str.toUpperCase(); });';
    put '}';
    put 'document.getElementById("reportModal").addEventListener("click", function(e) {';
    put '  if (e.target === this) {';
    put '    closeModal();';
    put '  }';
    put '});';
    put '</script>';
%mend generate_javascript_modal;

%macro generate_route_container;
    put '<div class="dashboard-grid">';
    put '<div id="main-panel" class="main-panel">';
    put '<!-- Content will be loaded dynamically by JavaScript -->';
    put '</div>';
    put '</div>';
%mend generate_route_container;

/* ============================================================================
   JAVASCRIPT ROUTING SYSTEM
   ============================================================================ */
%macro generate_javascript_routing;
    put '<script>';
    put '// Global routing variables';
    put 'var currentRoute = "#risk-categories";';
    put 'var routes = {';
    put '  "#risk-categories": getRiskCategoriesHTML,';
    put '  "#saccr-cva": function() { ';
    put '	const fields = [';
    put '	    { id: "asof", label: "As of Date", type: "date" }';
    put '	];';
    put '    return getpromptHTML("saccr-cva", "SACCR and CVA", "Quarterly regulatory report for SAMA compliance monitoring and risk assessment.", "Weekly / Monthly", fields);';
    put '  },';
    put '  "#sama-q17": function() { ';
    put '	const fields1 = [';
    put '	    { id: "asof", label: "As of Date", type: "date" },';
    put '	    { id: "report", label: "Report Pack", type: "select", options: ["Consolidated_Liquidity_Risk", "Consolidated_FRTB", "Consolidated_IRRBB", "Consolidated_Credit_Risk"]},';
    put '	    { id: "uploadDoc", label: "Upload Sheet", type: "file"},';
    put '	];';
    put '	const fields2 = [';
    put '	    { id: "RunType", label: "Run Type", type: "select", options: ["Weekly_Run", "Qtr_Run"]},';
    put '	    { id: "asof", label: "As of Date", type: "date" },';
    put '	    { id: "londonDate", label: "London Date", type: "date" }';
    put '	];';
    put '    let html = "";';
    put '    html += "<div style=''max-width: 1200px; margin: 0 auto; padding: 20px;''>";';
    put '    html += "<div style=''display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 25px; margin-bottom: 30px;''>";';
    put '    html += getpromptHTML("sama-q17", "SAMA Q17 Uploads", "Quarterly regulatory report for SAMA compliance monitoring and risk assessment.", "Quarterly", fields1);';
    put '    html += getpromptHTML("sama-q17-2", "SAMA Q17 Data Preparation", "Internal review and feedback submission for Q17 uploads.", "Quarterly", fields2);';
    put '    html += "</div></div>;"';
    put '    return html;';
    put '  },';
    put '  "#sama-p3": function() { ';
    put '	const fields = [';
    put '	    { id: "asof", label: "As of Date", type: "date" },';
    put '	    { id: "londonDate", label: "London Date", type: "date" }';
    put '	];';
    put '    return getpromptHTML("sama-p3", "SAMA Pillar 3 Data Preparation", "Quarterly regulatory report for SAMA compliance monitoring and risk assessment.", "Quarterly", fields);';
    put '  },';
    put '  "#assets": function() { ';
    put '	const fields1 = [';
    put '	    { id: "asof1", label: "As of Date", type: "date" },';
    put '	    { id: "asof2", label: "IFRS9", type: "date" },';
    put '	    { id: "asof3", label: "COMM_ADJ_DATE", type: "date" },';
    put '	    { id: "asof4", label: "ANBI DATE", type: "date" },';
    put '	    { id: "asof5", label: "LONDON DATE", type: "date" }';
    put '	];';
    put '	const fields2 = [';
    put '	    { id: "asof6", label: "As of Date", type: "date" },';
    put '	    { id: "asof7", label: "IFRS9", type: "date" },';
    put '	    { id: "asof8", label: "COMM_ADJ_DATE", type: "date" },';
    put '	    { id: "asof9", label: "ANBI DATE", type: "date" },';
    put '	    { id: "asof10", label: "LONDON DATE", type: "date" }';
    put '	];';
    put '    let html = "";';
    put '    html += "<div style=''max-width: 1200px; margin: 0 auto; padding: 20px;''>";';
    put '    html += "<div style=''display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 25px; margin-bottom: 30px;''>";';
    put '    html += getpromptHTML("asset1", "Assets before Adjustment", "Quarterly regulatory report for SAMA compliance monitoring and risk assessment.", "Quarterly", fields1);';
    put '    html += getpromptHTML("asset2", "Assets Reconcilation Process", "Internal review and feedback submission for Q17 uploads.", "Quarterly", fields2);';
    put '    html += "</div></div>;"';
    put '    return html;';
    put '  },';
    put '  "#liability": function() { ';
    put '	const fields = [';
    put '	    { id: "asof", label: "As of Date", type: "date" },';
    put '	    { id: "asofLN", label: "London Date", type: "date" }';
    put '	];';
    put '    return getpromptHTML("liability", "Liabilities Reconcilation Process", "Quarterly regulatory report for SAMA compliance monitoring and risk assessment.", "Weekly / Monthly", fields);';
    put '  },';
    put '  "#customer": function() { ';
    put '	const fields = [';
    put '	    { id: "asof", label: "As of Date", type: "date" },';
    put '	];';
    put '    return getpromptHTML("customer", "Customer MT", "Quarterly regulatory report for SAMA compliance monitoring and risk assessment.", "Weekly / Monthly", fields);';
    put '  },';
    put '  "#offbalance": function() { ';
    put '	const fields = [';
    put '	    { id: "asof1", label: "As of Date", type: "date" },';
    put '	    { id: "asofLN", label: "London Date", type: "date" },';
    put '	    { id: "firmDate", label: "Firm&Non Firm Date", type: "date" }';
    put '	];';
    put '    return getpromptHTML("offbalance", "Off Balance Reconcilation Process", "Quarterly regulatory report for SAMA compliance monitoring and risk assessment.", "Weekly / Monthly", fields);';
    put '  },';
    put '};';
    put '// Main routing function';
    put 'function showRoute(route) {';
    put '  console.log("Navigating to:", route);';
    put '  currentRoute = route;';
    put '  updateContent();';
    put '  // Update URL without page reload';
    put '  if (window.history && window.history.pushState) {';
    put '    window.history.pushState(null, null, route);';
    put '  }';
    put '}';
    put '// Update content based on current route';
    put 'function updateContent() {';
    put '  var mainPanel = document.getElementById("main-panel");';
    put '  if (!mainPanel) return;';
    put '  var routeFunction = routes[currentRoute];';
    put '  if (routeFunction && typeof routeFunction === "function") {';
    put '    mainPanel.innerHTML = routeFunction();';
    put '    // Initialize route-specific functionality';
    put '    if (currentRoute === "#saccr-cva") {';
    put '      setTimeout(function() { setDefaultDates("saccr-cva"); }, 100);';
    put '    } else if (currentRoute === "#sama-q17") {';
    put '      setTimeout(function() { setDefaultDates("sama-q17"); }, 100);';
    put '    } else if (currentRoute === "#sama-p3") {';
    put '      setTimeout(function() { setDefaultDates("sama-p3"); }, 100);';
    put '    }';
    put '  } else {';
    put '    mainPanel.innerHTML = "<div style=\"text-align: center; padding: 50px;\"><h2>Page Not Found</h2><p>The requested page could not be found.</p></div>";';
    put '  }';
    put '}';
    put '// Handle browser back/forward buttons';
    put 'window.addEventListener("popstate", function() {';
    put '  currentRoute = window.location.hash || "#risk-categories";';
    put '  updateContent();';
    put '});';
    put '// Initialize on page load';
    put 'document.addEventListener("DOMContentLoaded", function() {';
    put '  currentRoute = window.location.hash || "#risk-categories";';
    put '  updateContent();';
    put '});';
    put '</script>';
%mend generate_javascript_routing;

/* ============================================================================
   CONTENT GENERATORS
   ============================================================================ */
%macro generate_javascript_content_gen;
    put '<script>';

    put '// Risk Categories HTML Generator';
    put 'function getRiskCategoriesHTML() {';
    put '  var html = "";';
    put '  html += "<h2 style=''margin-bottom: 20px; color: #1f2937; font-size: 1.5rem;''>Master Table Preparation</h2>";';
    put '  html += "<div class=''risk-modules''>";';
    put '  html += "<div class=''risk-module'' data-module=''regulatory'' onclick=''showRoute(\"#saccr-cva\")''>";';
    put '  html += "<div class=''module-header''>";';
    put '  html += "<div class=''module-icon regulatory''><i class=''fas fa-gavel''></i></div>";';
    put '  html += "<h3 class=''module-title''>SACCR and CVA</h3>";';
    put '  html += "</div>";';
    put '  html += "<p class=''module-description''>Comprehensive regulatory compliance reports and monitoring dashboards for regulatory authorities.</p>";';
    put '  html += "<div class=''module-stats''>";';
    put '  html += "</div></div>";';
    put '  html += "<div class=''risk-module'' data-module=''credit'' onclick=''showRoute(\"#sama-q17\")''>";';
    put '  html += "<div class=''module-header''>";';
    put '  html += "<div class=''module-icon credit''><i class=''fas fa-credit-card''></i></div>";';
    put '  html += "<h3 class=''module-title''>SAMA Q17</h3>";';
    put '  html += "</div>";';
    put '  html += "<p class=''module-description''>Advanced credit risk assessment portfolio analysis and default probability modeling.</p>";';
    put '  html += "<div class=''module-stats''>";';
    put '  html += "</div></div>";';
    put '  html += "<div class=''risk-module'' data-module=''operational'' onclick=''showRoute(\"#sama-p3\")''>";';
    put '  html += "<div class=''module-header''>";';
    put '  html += "<div class=''module-icon operational''><i class=''fas fa-cogs''></i></div>";';
    put '  html += "<h3 class=''module-title''>SAMA Pillar III</h3>";';
    put '  html += "</div>";';
    put '  html += "<p class=''module-description''>Operational risk identification assessment and mitigation strategies across all business units.</p>";';
    put '  html += "<div class=''module-stats''>";';
    put '  html += "</div></div>";';
    put '  html += "<div class=''risk-module'' data-module=''market'' onclick=''showRoute(\"#assets\")''>";';
    put '  html += "<div class=''module-header''>";';
    put '  html += "<div class=''module-icon market''><i class=''fas fa-chart-line''></i></div>";';
    put '  html += "<h3 class=''module-title''>Assets</h3>";';
    put '  html += "</div>";';
    put '  html += "<p class=''module-description''>Real-time market risk monitoring VaR calculations and stress testing scenarios.</p>";';
    put '  html += "<div class=''module-stats''>";';
    put '  html += "<div class=''stat-item''><div class=''stat-value''>$45M</div><div class=''stat-label''>VaR (95%)</div></div>";';
    put '  html += "<div class=''stat-item''><div class=''stat-value''>12.5%</div><div class=''stat-label''>Volatility</div></div>";';
    put '  html += "</div></div>";';
    put '  html += "<div class=''risk-module'' data-module=''liquidity'' onclick=''showRoute(\"#liability\")''>";';
    put '  html += "<div class=''module-header''>";';
    put '  html += "<div class=''module-icon liquidity''><i class=''fas fa-water''></i></div>";';
    put '  html += "<h3 class=''module-title''>Liabilities</h3>";';
    put '  html += "</div>";';
    put '  html += "<p class=''module-description''>Liquidity risk assessment cash flow projections and funding stability analysis.</p>";';
    put '  html += "<div class=''module-stats''>";';
    put '  html += "<div class=''stat-item''><div class=''stat-value''>145%</div><div class=''stat-label''>LCR Ratio</div></div>";';
    put '  html += "<div class=''stat-item''><div class=''stat-value''>$850M</div><div class=''stat-label''>HQLA</div></div>";';
    put '  html += "</div></div>";';
    put '  html += "<div class=''risk-module'' data-module=''icaap'' onclick=''showRoute(\"#offbalance\")''>";';
    put '  html += "<div class=''module-header''>";';
    put '  html += "<div class=''module-icon icaap''><i class=''fas fa-balance-scale''></i></div>";';
    put '  html += "<h3 class=''module-title''>Off Balance Sheet</h3>";';
    put '  html += "</div>";';
    put '  html += "<p class=''module-description''>Internal Capital Adequacy Assessment Process and capital planning strategies.</p>";';
    put '  html += "<div class=''module-stats''>";';
    put '  html += "<div class=''stat-item''><div class=''stat-value''>18.5%</div><div class=''stat-label''>CAR</div></div>";';
    put '  html += "<div class=''stat-item''><div class=''stat-value''>$2.8B</div><div class=''stat-label''>Capital</div></div>";';
    put '  html += "</div></div>";';
    put '  html += "<div class=''risk-module'' data-module=''ilaap'' onclick=''showRoute(\"#customer\")''>";';
    put '  html += "<div class=''module-header''>";';
    put '  html += "<div class=''module-icon ilaap''><i class=''fas fa-tint''></i></div>";';
    put '  html += "<h3 class=''module-title''>Customer</h3>";';
    put '  html += "</div>";';
    put '  html += "<p class=''module-description''>Internal Liquidity Adequacy Assessment Process and liquidity risk management.</p>";';
    put '  html += "<div class=''module-stats''>";';
    put '  html += "<div class=''stat-item''><div class=''stat-value''>125%</div><div class=''stat-label''>NSFR</div></div>";';
    put '  html += "<div class=''stat-item''><div class=''stat-value''>$1.2B</div><div class=''stat-label''>Stable Funding</div></div>";';
    put '  html += "</div></div>";';
    put '  html += "</div>";';
    put '  return html;';
    put '}';

    put '// Dynamic Prompt Generator';
    put ' function getpromptHTML(reportId, title, description, frequency, fields) {';
    put '  var html = "";';
    put '  html += "<div style=''max-width: 1200px; margin: 0 auto; padding: 20px;''>";';
    put '  html += "<div style=''display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 25px; margin-bottom: 30px;''>";';
    put '  html += "<div style=''background: white; border-radius: 12px; padding: 25px; box-shadow: 0 4px 15px rgba(0, 0, 0, 0.08); border: 2px solid transparent; transition: all 0.3s ease; cursor: pointer;'' ";';
    put '  html += "onmouseover=''this.style.transform=\"translateY(-3px)\"; this.style.boxShadow=\"0 8px 25px rgba(0, 0, 0, 0.15)\"; this.style.borderColor=\"#3b82f6\";'' ";';
    put '  html += "onmouseout=''this.style.transform=\"translateY(0)\"; this.style.boxShadow=\"0 4px 15px rgba(0, 0, 0, 0.08)\"; this.style.borderColor=\"transparent\";'' ";';
    put '  html += "data-report=\" + reportId + \">";';
    put '  html += "<div style=''display: flex; align-items: flex-start; gap: 15px; margin-bottom: 20px;''>";';
    put '  html += "<div style=''width: 50px; height: 50px; background: linear-gradient(135deg, #3b82f6, #1d4ed8); border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 20px; color: white; flex-shrink: 0;''>";';
    put '  html += "<i class=\"fas fa-chart-bar\"></i>";';
    put '  html += "</div>";';
    put '  html += "<div style=''flex: 1;''>";';
    put '  html += "<h3 style=''font-size: 1.3rem; font-weight: 600; color: #1f2937; margin-bottom: 8px;''>" + title + "</h3>";';
    put '  html += "<p style=''color: #6b7280; font-size: 0.9rem; line-height: 1.5;''>" + description + "</p>";';
    put '  html += "</div>";';
    put '  html += "</div>";';
    put '  html += "<div style=''margin-bottom: 20px; padding: 15px; background: #f9fafb; border-radius: 8px;''>";';
    put '  html += "<div style=''display: flex; justify-content: space-between; align-items: center; padding: 8px 0; border-bottom: 1px solid #e5e7eb;''>";';
    put '  html += "<span style=''font-weight: 500; color: #374151;''>Frequency:</span>";';
    put '  html += "<span style=''color: #6b7280;''>" + frequency + "</span>";';
    put '  html += "</div>";';
    put '  if (fields && Array.isArray(fields)) {';
    put '    fields.forEach(function(field) {';
    put '      html += "<div style=''display: flex; justify-content: space-between; align-items: center; padding: 8px 0; border-bottom: 1px solid #e5e7eb;''>";';
    put '        html += "<span style=''font-weight: 500; color: #374151;''>" + field.label + ":</span>";';
    put '        if (field.type === "select") {';
    put '          html += "<select id=\"" + reportId + "-" + field.id + "\" style=\"color: #6b7280; font-size: 14px; border: none; background: transparent;\">";';
    put '            if (field.options && Array.isArray(field.options)) {';
    put '              field.options.forEach(function(opt) {';
    put '                html += "<option value=\"" + opt + "\">" + opt + "</option>";';
    put '              });';
    put '            }';
    put '          html += "</select>";';
    put '        } else {';
    put '          html += "<input type=\"" + field.type + "\" id=\"" + reportId + "-" + field.id + "\" style=\"color: #6b7280; font-size: 14px; border: none; background: transparent;\" />";';
    put '        }';
    put '      html += "</div>";';
    put '    });';
    put '  }';
    put '  html += "</div>";';
    put '  html += "<div style=''display: flex; gap: 10px;''>";';
    put '  html += "<button onclick=\"generateRegulatoryReport(''" + reportId + "'')\" style=\"padding: 10px 20px; border: none; border-radius: 8px; cursor: pointer; font-weight: 500; transition: all 0.3s ease; font-size: 0.9rem; background: #3b82f6; color: white;\" ";';
    put '  html += "onmouseover=\"this.style.background=''#2563eb''\" onmouseout=\"this.style.background=''#3b82f6''\">Run</button>";';
    put '  html += "<button onclick=\"viewReportHistory(''" + reportId + "'')\" style=\"padding: 10px 20px; border: none; border-radius: 8px; cursor: pointer; font-weight: 500; transition: all 0.3s ease; font-size: 0.9rem; background: #6b7280; color: white;\" ";';
    put '  html += "onmouseover=\"this.style.background=''#4b5563''\" onmouseout=\"this.style.background=''#6b7280''\">View History</button>";';
    put '  html += "</div>";';
    put '  html += "</div>";';
    put '  html += "</div>";';
    put '  return html;';
    put ' }';

    put '// Regulatory Report Generation Function';
    put 'function generateRegulatoryReport(reportType) {';
    put '  var dateInputId = reportType + "-asof";';
    put '  var dateInput = document.getElementById(dateInputId);';
    put '  if (!dateInput) {';
    put '    dateInputId = reportType + "-date";';
    put '    dateInput = document.getElementById(dateInputId);';
    put '  }';
    put '  if (!dateInput) {';
    put '    dateInputId = reportType + "-asof1";';
    put '    dateInput = document.getElementById(dateInputId);';
    put '  }';
    put '  var selectedDate = dateInput ? dateInput.value : null;';
    put '  console.log("Generating " + reportType + " report for date: " + selectedDate);';
    put '  if (!selectedDate || selectedDate.trim() === "") {';
    put '    showNotification("Please select a valid date for the report", "error");';
    put '    return;';
    put '  }';
    put '  showLoading();';
    put '  var params = { param_date: selectedDate };';
    put '  var formData = new URLSearchParams();';
    put '  formData.append("reporting_date", params.param_date);';
    put '  if (reportType === "sama-q17-2") {';
    put '    var londonDateInput = document.getElementById("sama-q17-2-londonDate");';
    put '    if (londonDateInput && londonDateInput.value) {';
    put '      formData.append("london_date", londonDateInput.value);';
    put '    }';
    put '  }';
    put '  if (reportType === "sama-p3") {';
    put '    var londonDateInput = document.getElementById("sama-p3-londonDate");';
    put '    if (londonDateInput && londonDateInput.value) {';
    put '      formData.append("london_date", londonDateInput.value);';
    put '    }';
    put '  }';
    put '  var storedProcedureUrl = "";';
    put '  if (reportType === "saccr-cva") {';
    put '    storedProcedureUrl = "https://enterprisebsl.anb.com.sa/SASStoredProcess/do?&_program=/User Folders/62917/My Folder/Master Tables Preparation/SACCR and CVA/SACCR_CVA_2";';
    put '  } else if (reportType === "sama-p3") {';
    put '    storedProcedureUrl = "https://enterprisebsl.anb.com.sa/SASStoredProcess/do?&_program=/User Folders/62917/My Folder/Market Risk/SAMA_P3_Report_Generator";';
    put '  }';
    put '  fetch(storedProcedureUrl, {';
    put '    method: "POST",';
    put '    headers: {';
    put '      "Content-Type": "application/x-www-form-urlencoded",';
    put '      "Accept": "text/html"';
    put '    },';
    put '    body: formData.toString()';
    put '  })';
    put '  .then(response => {';
    put '    if (!response.ok) {';
    put '      throw new Error("Network response was not ok: " + response.status);';
    put '    }';
    put '    console.log("Stored procedure executed successfully");';
    put '    return response.text();';
    put '  })';
    put '  .then(htmlResponse => {';
    put '    console.log("HTML Response received");';
    put '    showNotification("Master Table Prepared Successfully", "success");';
    put '    hideLoading();';
    put '  })';
    put '  .catch(error => {';
    put '    hideLoading();';
    put '    showNotification("Error generating Master Tables: " + error.message, "error");';
    put '  });';
    put '}';
    put '// View Report History Function';
    put 'function viewReportHistory(reportType) {';
    put '  console.log("Viewing report history for: " + reportType);';
    put '  showNotification("Report history feature coming soon", "info");';
    put '}';
    put '// Set default dates for date inputs if they are empty';
    put 'function setDefaultDates(reportType) {';
    put '  var today = new Date().toISOString().split("T")[0];';
    put '  var dateInputs = document.querySelectorAll("input[type=\"date\"]");';
    put '  dateInputs.forEach(function(input) {';
    put '    if (input.id && input.id.includes(reportType) && !input.value) {';
    put '      input.value = today;';
    put '    }';
    put '  });';
    put '}';

    put '</script>';
%mend generate_javascript_content_gen;
